# docker-compose.yml

version: '3.8' # docker-compose 파일 버전

services:
  # 서비스 이름 (원하는 대로 지정 가능, 예: db, postgres)
  db:
    # 사용할 이미지: PostGIS가 포함된 PostgreSQL 16 버전을 사용합니다.
    image: postgis/postgis:16-3.4
    
    # 컨테이너 이름
    container_name: ddareungimap-db

    # 컨테이너 환경 변수 설정
    environment:
      POSTGRES_USER: downy # 이전에 생성한 DB 사용자 이름
      POSTGRES_PASSWORD: du020817 # 이전에 생성한 DB 사용자 비밀번호
      POSTGRES_DB: ddareungimap_dev # 이전에 생성한 DB 이름

    # 포트 매핑 (호스트 포트:컨테이너 포트)
    # 내 컴퓨터(Mac)의 5432 포트를 컨테이너의 5432 포트와 연결합니다.
    ports:
      - "5432:5432"

    # 데이터 영속성을 위한 볼륨 설정
    # 이 설정을 해야 컨테이너를 삭제해도 데이터가 보존됩니다.
    volumes:
      - postgres-data:/var/lib/postgresql/data

    # 컨테이너가 예기치 않게 종료되면 항상 다시 시작
    restart: always

# Docker 볼륨 정의
volumes:
  postgres-data: